# These are supported funding model platforms
# Do these
github: <script>alert(1)</script> # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: <script>alert(1)</script> # Replace with a single Patreon username
open_collective: <script>alert(1)</script> # Replace with a single Open Collective username
ko_fi: <script>alert(1)</script> # Replace with a single Ko-fi username
tidelift: <script>alert(1)</script> # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: <script>alert(1)</script> # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: <script>alert(1)</script> # Replace with a single Liberapay username
issuehunt: <script>alert(1)</script> # Replace with a single IssueHunt username
lfx_crowdfunding: <script>alert(1)</script> # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: <script>alert(1)</script> # Replace with a single Polar username
buy_me_a_coffee: <script>alert(1)</script> # Replace with a single Buy Me a Coffee username
thanks_dev: <script>alert(1)</script> # Replace with a single thanks.dev username
custom: <script>alert(1)</script> # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
